// Make a self-contained folder to deploy the sponsor from (README: "Deploying").
//
// The compiled contract and its keys are generated by the Compact compiler and are not
// kept in git, so a deploy straight from GitHub would not have them. This copies what
// the service needs into one folder OUTSIDE the repository:
//   dist/                      the built service
//   artifacts/veilcore/        the compiled contract, and the anchorBatch keys only
//   package.json               the service's dependencies (same pinned versions)
// then `railway up <folder> --path-as-root` deploys exactly that.
//
// Usage: npm run stage -w sponsor [-- <target folder>]
// SPDX-License-Identifier: Apache-2.0

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const sponsorDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(sponsorDir, '..');
const target = resolve(process.argv[2] ?? join(repo, '..', 'veilcore-sponsor-deploy'));
const managed = join(repo, 'contract', 'src', 'managed', 'veilcore');

if (target.startsWith(repo + '/') || target === repo) {
  console.error(`Stage outside the repository (its .gitignore would hide files from the upload). Got ${target}`);
  process.exit(1);
}

const need = [
  join(managed, 'contract', 'index.js'),
  join(managed, 'keys', 'anchorBatch.prover'),
  join(managed, 'keys', 'anchorBatch.verifier'),
];
// The binary circuit file; made from the JSON one if the compiler did not write it.
if (!existsSync(join(managed, 'zkir', 'anchorBatch.bzkir'))) {
  if (!existsSync(join(managed, 'zkir', 'anchorBatch.zkir'))) need.push(join(managed, 'zkir', 'anchorBatch.bzkir'));
}
const missing = need.filter((f) => !existsSync(f));
if (missing.length > 0) {
  console.error('The compiled contract with keys is not here yet. Missing:');
  for (const f of missing) console.error(`  ${f}`);
  console.error('Compile the contract WITH keys first (cd contract && npm run compact), then run this again.');
  process.exit(1);
}

rmSync(target, { recursive: true, force: true });
mkdirSync(target, { recursive: true });
cpSync(join(sponsorDir, 'dist'), join(target, 'dist'), { recursive: true });

const art = join(target, 'artifacts', 'veilcore');
mkdirSync(join(art, 'contract'), { recursive: true });
mkdirSync(join(art, 'keys'), { recursive: true });
mkdirSync(join(art, 'zkir'), { recursive: true });
cpSync(join(managed, 'contract', 'index.js'), join(art, 'contract', 'index.js'));
for (const f of ['anchorBatch.prover', 'anchorBatch.verifier']) cpSync(join(managed, 'keys', f), join(art, 'keys', f));
cpSync(join(managed, 'zkir', 'anchorBatch.zkir'), join(art, 'zkir', 'anchorBatch.zkir'));
if (existsSync(join(managed, 'zkir', 'anchorBatch.bzkir'))) {
  cpSync(join(managed, 'zkir', 'anchorBatch.bzkir'), join(art, 'zkir', 'anchorBatch.bzkir'));
} else {
  const { jsonIrToBinary } = await import('@midnight-ntwrk/zkir-v2');
  writeFileSync(join(art, 'zkir', 'anchorBatch.bzkir'), jsonIrToBinary(readFileSync(join(managed, 'zkir', 'anchorBatch.zkir'), 'utf8')));
}
// The compiled contract is an ES module; say so for its folder.
writeFileSync(join(art, 'package.json'), JSON.stringify({ type: 'module' }, null, 2));

const own = JSON.parse(readFileSync(join(sponsorDir, 'package.json'), 'utf8'));
const root = JSON.parse(readFileSync(join(repo, 'package.json'), 'utf8'));
writeFileSync(
  join(target, 'package.json'),
  JSON.stringify(
    {
      name: own.name,
      version: own.version,
      private: true,
      type: 'module',
      license: own.license,
      engines: { node: '>=22' },
      scripts: { start: 'node dist/main.js' },
      dependencies: own.dependencies,
      overrides: root.overrides ?? {},
    },
    null,
    2,
  ),
);

try {
  execFileSync('npm', ['install', '--package-lock-only', '--ignore-scripts', '--no-audit', '--no-fund'], { cwd: target, stdio: 'inherit' });
} catch {
  console.warn('Could not write a lockfile (no network?). The deploy will still install, with the pinned versions.');
}

const sha = (f) => createHash('sha256').update(readFileSync(f)).digest('hex');
console.log(`\nStaged ${target}`);
console.log(`  contract/index.js         sha256 ${sha(join(art, 'contract', 'index.js'))}`);
console.log(`  keys/anchorBatch.verifier sha256 ${sha(join(art, 'keys', 'anchorBatch.verifier'))}`);
console.log('\nNext: railway up "' + target + '" --path-as-root --service veilcore-sponsor');
