// anchorBatch on the real network, for the anchoring job. Proving happens through the
// service's own proof server: anchorBatch has no secrets (its only input, the batch root,
// is public), so nothing private is sent there. The sponsor wallet pays the fee.
//
// The compiled contract is loaded from VEILCORE_ARTIFACTS_DIR at run time, because it is
// generated by the Compact compiler and is not kept in git (README: "Deploying").
// SPDX-License-Identifier: Apache-2.0

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import { ContractState } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import type { UnprovenTransaction } from '@midnight-ntwrk/ledger-v8';
import { createUnprovenCallTx } from '@midnight-ntwrk/midnight-js-contracts';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import type { AnchorChain, Landing, PreparedAnchor } from './anchorer.js';
import { lookupCall } from './lookup.js';
import type { FacadeWallet } from './wallet.js';

export type VeilcoreModule = typeof import('../../contract/src/managed/veilcore/contract/index.js');

export const loadVeilcore = async (artifactsDir: string): Promise<VeilcoreModule> => {
  const file = join(artifactsDir, 'contract', 'index.js');
  if (!existsSync(file)) {
    throw new Error(`No compiled VeilCore contract at ${file}. Set VEILCORE_ARTIFACTS_DIR (README: "Deploying").`);
  }
  return (await import(pathToFileURL(file).href)) as VeilcoreModule;
};

/** The anchoring job never holds a record secret. Any witness call is a bug, so it throws. */
const noSecrets = new Proxy(
  {},
  {
    get: (_t, name) => () => {
      throw new Error(`the anchoring job holds no secrets (witness ${String(name)} was asked for)`);
    },
  },
);

const WITNESS_NAMES = [
  'localGeneticSecret',
  'incomingGeneticSecret',
  'recoverySecret',
  'licenseSecret',
  'licenseRecord',
  'licensePath',
  'presentationChallenge',
] as const;

const PRIVATE_STATE_ID = 'anchorer';

/** A private-state store with nothing in it but a placeholder (anchorBatch reads none). */
const emptyPrivateState = () => {
  const states = new Map<string, unknown>();
  return {
    setContractAddress: () => undefined,
    get: (id: string) => Promise.resolve(states.get(id) ?? null),
    set: (id: string, s: unknown) => {
      states.set(id, s);
      return Promise.resolve();
    },
    remove: (id: string) => {
      states.delete(id);
      return Promise.resolve();
    },
    clear: () => {
      states.clear();
      return Promise.resolve();
    },
    getSigningKey: () => Promise.resolve(null),
    setSigningKey: () => Promise.resolve(),
    removeSigningKey: () => Promise.resolve(),
    clearSigningKeys: () => Promise.resolve(),
  };
};

export class MidnightAnchorChain implements AnchorChain {
  private readonly publicData;
  private readonly zk;
  private readonly prover;
  private readonly privateState = emptyPrivateState();
  private readonly compiled;

  constructor(
    private readonly veilcore: VeilcoreModule,
    private readonly artifactsDir: string,
    private readonly contractAddress: string,
    private readonly indexer: string,
    indexerWS: string,
    proofServer: string,
    private readonly wallet: FacadeWallet,
    private readonly coinPublicKey: string,
    private readonly encryptionPublicKey: string,
    /** Tests only: stand-ins for the indexer and the proof server. */
    overrides: { publicData?: unknown; prover?: unknown } = {},
  ) {
    this.publicData = (overrides.publicData as ReturnType<typeof indexerPublicDataProvider>) ?? indexerPublicDataProvider(indexer, indexerWS);
    this.zk = new NodeZkConfigProvider<'anchorBatch'>(artifactsDir);
    this.prover = (overrides.prover as ReturnType<typeof httpClientProofProvider>) ?? httpClientProofProvider(proofServer, this.zk);
    const witnesses = Object.fromEntries(WITNESS_NAMES.map((n) => [n, (noSecrets as Record<string, unknown>)[n]]));
    this.compiled = CompiledContract.make('Veilcore', veilcore.Contract).pipe(
      CompiledContract.withWitnesses(witnesses as never),
      CompiledContract.withCompiledFileAssets(artifactsDir as never),
    );
  }

  /** The contract as it stands: its maintenance committee, and whether our anchorBatch key matches the chain's. */
  async contractCheck(): Promise<{ committee: string[]; anchorBatchKeyMatches: boolean; operations: string[] }> {
    const state = await this.publicData.queryContractState(this.contractAddress);
    if (!state) throw new Error(`No contract at ${this.contractAddress} on this network.`);
    const op = state.operation('anchorBatch');
    const local = readFileSync(join(this.artifactsDir, 'keys', 'anchorBatch.verifier'));
    const ops = state.operations().map((o) => (typeof o === 'string' ? o : Buffer.from(o).toString('utf8')));
    return {
      committee: [...state.maintenanceAuthority.committee],
      anchorBatchKeyMatches: op !== undefined && Buffer.from(op.verifierKey).equals(local),
      operations: ops,
    };
  }

  private ledgerOf = (stateHex: string) => {
    const l = this.veilcore.ledger(ContractState.deserialize(Uint8Array.from(Buffer.from(stateHex, 'hex'))).data);
    return { lastBatchRoot: Buffer.from(l.lastBatchRoot).toString('hex'), batchSeq: l.batchSeq };
  };

  async batchSeq(): Promise<bigint> {
    const state = await this.publicData.queryContractState(this.contractAddress);
    if (!state) throw new Error('contract not found');
    return this.veilcore.ledger(state.data).batchSeq;
  }

  async prepare(rootHex: string): Promise<PreparedAnchor> {
    await this.privateState.set(PRIVATE_STATE_ID, {});
    const providers = {
      publicDataProvider: this.publicData,
      zkConfigProvider: this.zk,
      privateStateProvider: this.privateState,
      walletProvider: {
        getCoinPublicKey: () => this.coinPublicKey,
        getEncryptionPublicKey: () => this.encryptionPublicKey,
        balanceTx: () => Promise.reject(new Error('not used')),
      },
    };
    const data = await createUnprovenCallTx(providers as never, {
      compiledContract: this.compiled,
      contractAddress: this.contractAddress,
      circuitId: 'anchorBatch',
      args: [Uint8Array.from(Buffer.from(rootHex, 'hex'))],
      privateStateId: PRIVATE_STATE_ID,
    } as never);
    const unproven = (data as { private: { unprovenTx: UnprovenTransaction } }).private.unprovenTx;
    const proven = await this.prover.proveTx(unproven);
    const ttl = new Date(Date.now() + 30 * 60_000);
    const finalized = await this.wallet.balanceUnbound(proven, ttl);
    const [txId] = finalized.identifiers();
    return {
      txId,
      ttl,
      submit: async () => {
        await this.wallet.submit(finalized);
      },
      abandon: () => this.wallet.revert(finalized),
    };
  }

  lookup(txId: string): Promise<Landing> {
    return lookupCall(this.indexer, this.contractAddress, txId, 'anchorBatch', this.ledgerOf);
  }
}
